'''Manage Apache virtual hosts for Appy sites on target machines'''

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# ~license~

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
import os
from pathlib import Path

from appy.utils.string import Variables
from appy.utils.path import getTempFileName

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Template virtual host for http (to avoid)
httpSingle = '''<VirtualHost *:80>
 ServerName |domain|
 ServerAdmin |email|
 ErrorLog ${APACHE_LOG_DIR}/error.log
 CustomLog ${APACHE_LOG_DIR}/access.log combined
 RewriteEngine on
 RewriteRule ^(.*) http://localhost:|port|$1 [P]
</VirtualHost>
<Proxy "http://localhost:|port|">
 ProxySet keepalive=On responsefieldsize=16384
</Proxy>'''

# Template virtual host for http (redirect to https)
http = '''<VirtualHost *:80>
 ServerName |domain|
 RedirectPermanent / https://|domain|/
</VirtualHost>'''

# Template virtual host for https
#
# Within the Proxy directive, responsefieldsize is greater than the default,
# being 8192 (8Kb). This is because Appy uses cookies to store textual messages
# returned to the browser. Often, these messages contain more than 8Kb.

https = '''<IfModule mod_ssl.c>
 <VirtualHost _default_:443>
  ServerName |domain|
  ServerAdmin |email|
  ErrorLog ${APACHE_LOG_DIR}/error.log
  CustomLog ${APACHE_LOG_DIR}/access.log combined
  SSLEngine on
  ProxyTimeout 10800
  SSLCertificateFile |destCert|
  SSLCertificateKeyFile |destKey|
  SSLCertificateChainFile |destChain|
  SSLCACertificateFile |destChain|
  RewriteEngine on
  RewriteRule ^(.*) http://localhost:|port|$1 [P]
 </VirtualHost>
 <Proxy "http://localhost:|port|">
  RequestHeader set X-Forwarded-Proto "https"
  ProxySet keepalive=On responsefieldsize=16384
 </Proxy>
</IfModule>'''

templates = {'httpSingle': httpSingle, 'http': http, 'https': https}

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
APA_P_KO  = '"apache" option not applied: unknown protocol: %s.'

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
class Config:
    '''Configuration elements being requested to generate an Apache virtual
       host.'''

    # Names of the attributes storing HTTPS-related certificate files
    fileAttributes = 'cert', 'key', 'chain'

    def __init__(self, email, domain, protocol='https', cert=None, key=None,
                 chain=None, destFolder='ssl'):
        # The email address identifying the software creator managing the site
        self.email = email
        # The server's domain name, as known and accessed by the end users
        self.domain = domain
        # The protocol in use between end users and the server: should be
        # 'https' and not 'http', but both are supported.
        self.protocol = protocol
        # [https] There are 2 main cases for managing certificates :
        #         (1) the certificate, private key and chain files are on the
        #             DEV machine ;
        #         (2) these files already lie on the server itself (ie, they
        #             were generated by a nice tool like certbox from EFF/Let's
        #             Encrypt).
        #
        # In case (1), p_cert, p_key and p_chain must hold, as strings or Path
        #              objects, absolute paths to, respectively, the
        #              certificate, private key and chain files, that must lie
        #              on the DEV machine. These files will be copied to the
        #              server at a place determined by p_destFolder (see below).
        #
        # In case (2), p_cert, p_key and p_chain must hold, as string, simple
        #              file names (not including any path info) for the same
        #              files, that are expected to be found on the server
        #              himself, in p_destFolder (see below).
        #
        self.cert  = str(cert)  if cert  else None # Could be a Path object
        self.key   = str(key)   if key   else None
        self.chain = str(chain) if chain else None
        # [https] In case (1), p_destFolder must contain, as a string, the name
        #                      of the destination folder, within
        #                      Apache.configFolder, where to copy certificate-
        #                      related files. Set a simple name here, not a
        #                      path.
        #         In case (2), p_destFolder must contain, as a string, the
        #                      absolute path to the certificate-related files
        #                      (ie, "/etc/letsencrypt/live/<some_name>"). So
        #                      ensure p_destFolder starts with a '/' in that
        #                      case.
        self.destFolder = destFolder
        # Must we copy cert-related files from the DEV machine to the server ?
        self.copyFiles = not destFolder.startswith('/')
        # Set Path objects for certificate files
        if protocol == 'https':
            self.setPaths()

    def setPaths(self):
        '''Set Path objects for certificate files'''
        dest = self.destFolder
        if self.copyFiles:
            # We are in case (1), see constructor. Compute, as a Path object,
            # the absolute path to the folder, on the server, where certificate-
            # related files will be copied from the DEV machine.
            self.destPath = Path(Apache.configFolder) / dest
            # Store the absolute paths to these files as copied on the server
            for name in self.fileAttributes:
                local = getattr(self, name) # The file path on the DEV machine
                distant = self.destPath / Path(local).name
                setattr(self, f'dest{name.capitalize()}', str(distant))
        else:
            # We are in case (2), see constructor
            for name in self.fileAttributes:
                fileName = getattr(self, name)
                path = Path(dest) / fileName
                # Compute the absolute path to the file on the server
                setattr(self, f'dest{name.capitalize()}', str(path))

#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
class Apache:
    '''Represents an Apache virtual host to create or update for some Appy site
       on some target.'''

    # The folder where virtual hosts reside
    configFolder = '/etc/apache2'
    sitesFolder = f'{configFolder}/sites-enabled'

    # Restart command
    restart = 'apache2ctl restart'

    def __init__(self, target):
        self.target = target

    def get(self, config, template):
        '''Creates, from this p_template, the content of a virtual host, and
           dump it in a temp file. The method returns the path to this temp
           file.'''
        content = Variables.replace(template, config)
        path = getTempFileName()
        with open(path, 'w') as f: f.write(content)
        return path

    def copyVirtualHost(self, typE, config, target):
        '''Copy a virtual host of this p_type to the p_target'''
        # Dump the virtual host definition in a local temp file
        template = templates[typE]
        localPath = self.get(config, template)
        suffix = '' if typE == 'httpSingle' else f'_{typE}'
        dest = f'{Apache.sitesFolder}/{target.siteName}{suffix}.conf'
        target.copy(localPath, dest)
        os.remove(localPath)

    def deploy(self):
        '''Creates a virtual host and deploys it (copy + configure) on
           p_self.target.'''
        target = self.target
        config = target.apache
        # Set the site port on the v_config. Else, it will not be found by the
        # code (see m_get) that must inject it into the virtual host template
        # string.
        config.port = str(target.sitePort)
        if config.protocol == 'http':
            # Create a unique http virtual host
            self.copyVirtualHost('httpSingle', config, target)
            # Restart Apache
            target.execute(Apache.restart)
        elif config.protocol == 'https':
            # Create a virtual host that will redirect http traffic to https,
            # and a second one that manages https.
            for typE in ('http', 'https'):
                self.copyVirtualHost(typE, config, target)
            # [Case 2] Copy certificate files to the target. Overwrite any
            #          existing file. As a preamble, ensure the destination
            #          folder for these files exist.
            if config.copyFiles:
                target.execute(f'mkdir -p {config.destPath}')
                for name in config.fileAttributes:
                    dest = getattr(config, f'dest{name.capitalize()}')
                    target.copy(getattr(config, name), dest)
            # Restart Apache
            target.execute(Apache.restart)
        else:
            print(APA_P_KO % config.protocol)
            return
#- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
